# Generated by Django 4.1.2 on 2022-10-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('postponed', 'Postponed'), ('delayed', 'Delayed'), ('complted', 'Completed')], default='in_progress', max_length=20),
        ),
    ]
