# Generated by Django 4.1.2 on 2022-10-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('on_track', 'On track '), ('postponed', 'Postponed'), ('delayed', 'Delayed'), ('complted', 'Completed')], default='on_track', max_length=20),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('on_track', 'On track '), ('postponed', 'Postponed'), ('delayed', 'Delayed'), ('complted', 'Completed')], default='in_progress', max_length=20)),
                ('start_date', models.DateField()),
                ('deadline_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.project')),
            ],
        ),
    ]
