# Generated by Django 4.1.2 on 2022-10-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_project_status_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('high', 'High')], default='normal', max_length=10),
        ),
    ]
