# Generated by Django 4.1.2 on 2022-10-29 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_alter_module_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='module',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('postponed', 'Postponed'), ('delayed', 'Delayed'), ('complted', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('postponed', 'Postponed'), ('delayed', 'Delayed'), ('complted', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.CreateModel(
            name='ModuleTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.employee')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.module')),
            ],
        ),
    ]
