# Generated by Django 4.1.2 on 2022-10-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_module_module_leader_alter_module_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleteam',
            name='module',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], max_length=255),
        ),
    ]
