# Generated by Django 4.1.2 on 2022-10-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_moduleteam_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleteam',
            name='module',
            field=models.CharField(choices=[('Billing system project', ()), ('Project management tool', ())], max_length=255),
        ),
    ]
