# Generated by Django 4.1.2 on 2022-10-29 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_moduleteam_project_alter_moduleteam_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleteam',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.project'),
        ),
    ]
